bingo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/urls.py
from django.urls import path 
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('sortear/', views.sortear, name='sortear'),
    path('cartelas/', views.cartelas, name='cartelas'),
    path('compartilhar/<str:rede>', views.compartilhar, name='compartilhar'),
    path('comentario/', views.comentario, name='comentario') 
]

core/models.py
from django.db import models


class Silaba(models.Model):
    silaba = models.CharField(max_length=3)
    palavra1 = models.CharField(max_length=10, blank=True, null=True)
    palavra2 = models.CharField(max_length=10, blank=True, null=True)
    imagem1 = models.ImageField(upload_to='silabas', blank=True, null=True)
    imagem2 = models.ImageField(upload_to='silabas', blank=True, null=True)

    class Meta:
        ordering = ('silaba',)

    def __str__(self):
        return self.silaba


class Metrica(models.Model):
    mes = models.IntegerField()
    ano = models.IntegerField()
    sorteios = models.BigIntegerField(default=0)    
    facebook = models.BigIntegerField(default=0)
    twitter = models.BigIntegerField(default=0)
    whatsapp = models.BigIntegerField(default=0)
    telegram = models.BigIntegerField(default=0)
    email = models.BigIntegerField(default=0)

    class Meta:
        ordering = ('mes', 'ano')
        unique_together = ['mes', 'ano']

    def __str__(self):
        return f'{str(self.mes)}-{str(self.ano)}'


class Comentario(models.Model):
    TIPO_CHOICES = (
        ('E', 'Elogio'),
        ('D', 'Dúvida'),
        ('R', 'Reclamação'),
        ('S', 'Sugestão'),
        ('X', 'Outros'),
    )
    nome = models.CharField(max_length=100)
    email = models.EmailField(blank=True, null=True)
    tipo = models.CharField(max_length=1, choices=TIPO_CHOICES)
    mensagem = models.TextField()
    publicado = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-publicado',)

    def __str__(self):
        return self.nome

core/forms.py
from django import forms

from .models import Comentario


class ComentarioForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = ('nome', 'email', 'tipo', 'mensagem')
        labels = {
            'email': ('E-mail (opcional)'),
        }

core/views.py
from django.shortcuts import render
from django.core import serializers
from django.contrib.sessions.models import Session
from .models import Silaba, Metrica, Comentario
from .forms import ComentarioForm
from datetime import datetime
import random

list_silabas = []
list_sorteadas = []

def serialize_object(obj):
    return serializers.serialize('json', obj)
    
def deserialize_object(obj):
    silaba_obj = []
    for d_obj in serializers.deserialize('json', obj):
        silaba_obj.append(d_obj.object)
    return silaba_obj

def home(request):
    request.session.flush()
    request.session['silabas'] = serialize_object(Silaba.objects.all())
    request.session.modified = True
    return render(request, 'home.html')

def publicar_metrica():
    mes_hoje = datetime.today().month
    ano_hoje = datetime.today().year
    return Metrica.objects.filter(mes=mes_hoje,ano=ano_hoje)

def silaba_escolhida(lista):
    silaba = random.choice(lista)
    lista.remove(silaba)
    return silaba

def sortear(request):
    metrica = publicar_metrica()
    n_sorteio = metrica[0].sorteios + 1
    metrica.update(sorteios=n_sorteio)
    ######
    silabas = deserialize_object(request.session.get('silabas')) if request.session.get('silabas') != None else []
    if len(silabas) == 0:
        escolhida = None
        sorteadas = []
    else:
        escolhida = random.choice(silabas)
        silabas.remove(escolhida)
        sorteadas = deserialize_object(request.session.get('sorteadas')) if request.session.get('sorteadas') != None else []
        sorteadas.append(escolhida)
        request.session['silabas'] = serialize_object(silabas)
        request.session['sorteadas'] = serialize_object(sorteadas)
        sorteadas = deserialize_object(request.session.get('sorteadas'))
        request.session.modified = True
    return render(request, 'sorteio.html', {
        'silaba_escolhida': escolhida,
        'sorteadas': sorteadas,
        'num_sorteadas': len(sorteadas),
    })

def cartelas(request):
    dic = {}
    for i in range(6):
        lista = list(Silaba.objects.all())
        arr = [[ silaba_escolhida(lista).silaba for n in range(4) ] for n in range(3)]
        dic[i] = arr
    return render(request, 'cartelas.html',{
        'dic': dic,
    })

def compartilhar(request, rede):
    metrica = publicar_metrica()
    if rede == 'facebook':
        n_facebook = metrica[0].facebook + 1
        metrica.update(facebook=n_facebook)
    elif rede == 'twitter':
        n_twitter = metrica[0].twitter + 1
        metrica.update(twitter=n_twitter)
    elif rede == 'whatsapp':
        n_whatsapp = metrica[0].whatsapp + 1
        metrica.update(whatsapp=n_whatsapp)
    elif rede == 'telegram':
        n_telegram = metrica[0].telegram + 1
        metrica.update(telegram=n_telegram)
    elif rede == 'email':
        n_email = metrica[0].email + 1
        metrica.update(email=n_email)
    return render(request, 'compartilhamento.html', {
        'rede': rede,
    })

def comentario(request):
    novo_comentario = None
    if request.method == 'POST':
        comentario_form = ComentarioForm(data=request.POST)
        if comentario_form.is_valid():
            novo_comentario = comentario_form.save(commit=False)
            novo_comentario.save()
    else:
        comentario_form = ComentarioForm()
    return render(request, 'comentario.html', {
        'novo_comentario': novo_comentario,
        'comentario_form': comentario_form
    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-171663905-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-171663905-1');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Bingo de Sílabas - Um passatempo para se divertir com as crianças e com a família"/>
    <meta name="keywords" content="bingo, familia, jogo, crianças, jogos educativos"/>
    <meta name="robots" content="index, follow">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css" /> -->
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"> 
    <!-- Favicons -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicons/favicon.ico' %}"/>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicons/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- # -->
    <title>Bingo das Sílabas</title>
    <script language="javascript" type="text/javascript">

        function popitup(url, name) {
            newwindow=window.open(url,name,'height=400,width=600');
            if (window.focus) { newwindow.focus() }
            return false;
        }

    </script>
</head>
{% block home %}
{% endblock %}
</html>

templates/cartelas.html
{% extends "base.html" %}

{% block title %}Bingo das Sílabas - Cartelas{% endblock %}
{% block home %}
<body>
    <div class="container-fluid">
        <p style="text-align: center; background-color: unset;">
            <a href="#" onclick="window.print();">CLIQUE AQUI</a> PARA IMPRIMIR, DEPOIS BASTA FECHAR ESSA JANELA PARA VOLTAR P/ O BINGO
        </p>
        <div class="row justify-content-center">
        {% for k, v in dic.items %}
            <div class="col-md-6">
                <table class="table table-bordered table-sm">
                    <tbody>
                        {% for item in v %}
                        <tr style="text-align: center; font-size: 2.2em;">
                            {% for silaba in item %}
                            <td><strong>{{ silaba }}</strong></td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
        </div>
     </div>
</body>
{% endblock %}

templates/comentario.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Bingo das Sílabas - Comentário{% endblock %}
{% block home %}
<div class="container-fluid">
  <div class="jumbotron">
      <div class="row justify-content-center">
          <div class="col-md-6">              
              <h1 class="display-3" style="text-align: center;">Bingo das Sílabas</h1>
              {% if novo_comentario %}
                <h2 style="text-align: center;">Muito obrigado pelo seu comentário!</h2>
              {% else %}
                <h2 style="text-align: center;">Registre aqui o seu comentário</h2>
                <form method="POST">
                  {% csrf_token %}
                  {{ comentario_form|crispy }}
                  <input class="btn btn-success" type="submit" value="Enviar" />
                </form>
              {% endif %}
              <p style="text-align: center;"><a class="btn btn-lg btn-outline-primary" href="{% url "core:home" %}" role="button">VOLTAR P/ HOME</a></p>
          </div>
      </div>
  </div>
</div>
{% endblock %}

templates/compartilhamento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compartilhamento</title>
    <script type="text/javascript"> 
        function redirectShare() {
            {% if rede == 'facebook' %}
                window.location = "https://www.facebook.com/sharer/sharer.php?u={{ request.scheme }}://{{ request.get_host }}{% url 'core:home' %}"
            {% elif rede == 'twitter' %}
                window.location = "https://twitter.com/intent/tweet?url={{ request.scheme }}://{{ request.get_host }}{% url 'core:home' %}&text=Bingo das Sílabas"
            {% elif rede == 'whatsapp' %}
                window.location = "https://web.whatsapp.com/send?text=Bingo das Sílabas {{ request.scheme }}://{{ request.get_host }}{% url 'core:home' %}"
            {% elif rede == 'telegram' %}
                window.location = "https://t.me/share/url?url={{ request.scheme }}://{{ request.get_host }}{% url 'core:home' %}&text=Bingo das Sílabas"
            {% elif rede == 'email' %}
            window.location = "mailto:?subject=Bingo&nbsp;das&nbsp;S&iacute;labas&amp;body={{ request.scheme }}://{{ request.get_host }}{% url 'core:home' %}"
            {% endif %}
        }
    </script>
</head>
<body onload="setTimeout('redirectShare()',500)">
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block home %}
<body>
    <div class="container-fluid">
        <div class="jumbotron">
            {% block content %}
            {% endblock %}
            <div class="row justify-content-center">
                <div class="col-md-12">
                    {% if 'sortear' not in request.get_full_path %}
                    <p class="lead" style="text-align: center;">Venha se divertir com as crianças e a família no:</p>
                    <h1 class="display-3" style="text-align: center;">Bingo das Sílabas</h1>
                    <p class="lead" style="text-align: center;">Clique em "Sortear" para começar o jogo e para sortear uma nova sílaba</p>
                    <br/>
                    <p style="text-align: center;"><a class="btn btn-lg btn-success" href="{% url "core:sortear" %}" role="button">SORTEAR</a></p>
                    {% else %}
                    <br />
                    <p style="text-align: center;"><a class="btn btn-lg btn-success" href="{% url "core:sortear" %}" role="button">SORTEAR (OU APERTE F5)</a></p>
                    {% endif %}
                    {% block button %}
                    {% endblock %}
                    <p style="text-align: center;"><a class="btn btn-lg btn-primary" href="{% url "core:cartelas" %}" target="_blank" role="button">GERAR CARTELAS</a></p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-3">
                <p style="text-align: center; background-color: unset;">
                    DEIXE AQUI O SEU <a href="{% url "core:comentario" %}">COMENTÁRIO</a> E COMPARTILHE
                </p>
                <p style="text-align: center;">
                    <a class="btn btn-lg btn-social btn-fb" href="#" onclick="return popitup('{% url 'core:compartilhar' rede='facebook' %}','facebook')" title="Compartilhe esta página no Facebook">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                    <a class="btn btn-lg btn-social btn-tw" href="#" onclick="return popitup('{% url 'core:compartilhar' rede='twitter' %}','twitter')" title="Compartilhe esta página no Twitter">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="btn btn-lg btn-social btn-wa" href="#" onclick="return popitup('{% url 'core:compartilhar' rede='whatsapp' %}','whatsapp')" title="Compartilhe esta página no WhatsApp">
                        <i class="fab fa-whatsapp"></i>
                    </a>
                    <a class="btn btn-lg btn-social btn-te" href="#" onclick="return popitup('{% url 'core:compartilhar' rede='telegram' %}','telegram')" title="Compartilhe esta página no Telegram">
                        <i class="fab fa-telegram"></i>
                    </a>
                    <a class="btn btn-lg btn-social btn-ma" href="#" onclick="return popitup('{% url 'core:compartilhar' rede='email' %}','email')" title="Compartilhe esta página por email">
                        <i class="fa fa-envelope"></i>
                    </a>
                </p>
                <p style="text-align: center;">
                    © 2020 Thiago Ozores <a href="https://github.com/ozorest"><i class="fab fa-github"></i></a>&nbsp;<a href="https://www.linkedin.com/in/tozores"><i class="fab fa-linkedin"></i></a><br />
                </p>
            </div>
        </div>
    </div> 
</body>
{% endblock %}

templates/sorteio.html
{% extends "home.html" %}

{% block button %}
    <p style="text-align: center;"><a class="btn btn-lg btn-danger" href="{% url "core:home" %}" role="button">RECOMEÇAR</a></p>
{% endblock %}

{% block content %}
<div class="container-fluid">
    {% if silaba_escolhida != None %}
    <div class="row justify-content-center">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <h1 style="text-align: center; font-size: 10em;">
                <span class="badge badge-info">{{ silaba_escolhida.silaba }}</span>
            </h1>
        </div>
        <div class="col-md-4">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header" style="text-align: center;">
                    Sorteadas  ({{ num_sorteadas }})
                </h5>
                <div class="card-body">
                    <p class="card-text">
                        {% for s in sorteadas %}
                        <span class="badge badge-warning" style="font-size: 2em; margin-bottom: 0.25em;">{{ s }}</span>
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2 style="text-align: center;">
                <span class="badge badge-danger">Não há mais sílabas para sortear, <a href="{% url "core:home" %}">clique aqui para recomeçar</a></span>
            </h2>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}